---
title: "4.X_visualizeEstimatorRes"
format: 
  html:
    theme: flatly
    toc: true
editor: source
execute: 
  echo: false
  warning: false
  error: false
---







# Load


```{r output=FALSE}
suppressPackageStartupMessages(library(assertthat)) # for some assert statements
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggh4x))


theme_set(theme_cowplot() +
            theme(plot.title = element_text(hjust = .5),
                  plot.subtitle = element_text(hjust = .5),
                  strip.background = element_rect(fill = "white", color = 'black'),
                  panel.grid.minor = element_blank(),
                  panel.grid.major = element_blank()))



# parameters
DEVICE                = 'laptop'
AYZW_setting_name     = 'A'


source('../PATHS.R') # load in data_dir and save_dir and CODE_DIR, depending on DEVICE value


# Continuous
# ========================================================================================================================================================================

proximal_setting_name = 'simple'
plot_dir_continuous = sprintf('%s/AY/%s/%s/plots/', save_dir, AYZW_setting_name, proximal_setting_name) # create plot_dir (based on save_dir + settings)
dir.create(plot_dir_continuous, showWarnings = FALSE)


# config colors for plot
method_long_colors = c( colorRampPalette(c('white', 'forestgreen'))(8)[c(4, 8)], 
                        viridis::plasma(10)[c(3, 4, 5, 6, 7, 8, 9)])
barplot(1:length(method_long_colors), col = method_long_colors)


effects_continuous = read.csv(sprintf('%s/AY/%s/%s/effects_continuous.csv', save_dir, AYZW_setting_name, proximal_setting_name))
effects_continuous = effects_continuous |> mutate(method_long = paste0(method, numNC))



effects_continuous$method_long = factor(effects_continuous$method_long, 
       levels = c( "lmYANA",                 "lmYAUNA" ,       "2SLSpci2s1",       "2SLSpci2s3",       "2SLSpci2s5",       "2SLSpci2s10",       "2SLSpci2s15",       "2SLSpci2s20"),
       labels = c("Lin Reg", "Lin Reg (w/ confounders)", "Proximal (#NC=1)", "Proximal (#NC=3)", "Proximal (#NC=5)", "Proximal (#NC=10)", "Proximal (#NC=15)", "Proximal (#NC=20)"))

effects_continuous$type = factor(effects_continuous$type,
       levels = c('negative', 'positive'),
       labels = c(    'Null', 'Alternative'))

dim(effects_continuous); head(effects_continuous)


# Count GLM
# ========================================================================================================================================================================
proximal_setting_name = 'simpleCount'


plot_dir_count = sprintf('%s/AY/%s/%s/plots/', save_dir, AYZW_setting_name, proximal_setting_name) # create plot_dir (based on save_dir + settings)
dir.create(plot_dir_count, showWarnings = FALSE)



# config colors for plot
method_long_colors_count = c(colorRampPalette(c('white', 'darkblue'))(8)[c(4, 8)], #light blue, darker blue
                             colorRampPalette(c('white', 'darkcyan'))(8)[c(4, 8)]  #light teal, darker teal
                             )
barplot(1:length(method_long_colors_count), col = method_long_colors_count)


effects_count = read.csv(sprintf('%s/AY/%s/%s/effects_countGLM.csv', save_dir, AYZW_setting_name, proximal_setting_name))
effects_count = effects_count |> mutate(method_long = paste0(method, numNC))

effects_count$method_long = factor(effects_count$method_long, 
       levels = c( "poisYANA",  "poisYAUNA", "nbYANA", "nbYAUNA"),
       labels = c("Poisson", "Poisson (w/ confounders)", "Negative Binomial", "Negative Binomial (w/ confounders)"))



effects_count$type = factor(effects_count$type,
       levels = c('negative', 'positive'),
       labels = c(    'Null', 'Alternative'))


dim(effects_count); head(effects_count)


# All
# ========================================================================================================================================================================

# save results of 'all' together in continuous folder
proximal_setting_name = 'simple'
plot_dir_all = sprintf('%s/AY/%s/%s/plotsAll/', save_dir, AYZW_setting_name, proximal_setting_name) # create plot_dir (based on save_dir + settings)
dir.create(plot_dir_all, showWarnings = FALSE)





effects = rbind(effects_continuous, effects_count)




# config colors for plot
method_long_colors_all = c(method_long_colors_count, method_long_colors)
barplot(1:length(method_long_colors_all), col = method_long_colors_all)



effects = effects |> mutate(method_long = paste0(method, numNC))



effects$method_long = factor(effects$method_long, 
       levels = c("poisYANA",      "poisYAUNA", "nbYANA",           "nbYAUNA",                             "lmYANA",                            "lmYAUNA" ,       
                         "2SLSpci2s1",       "2SLSpci2s3",       "2SLSpci2s5",       "2SLSpci2s10",       "2SLSpci2s15",       "2SLSpci2s20"),
       labels = c( "Poisson", "Poisson (w/ confounders)", "Negative Binomial", "Negative Binomial (w/ confounders)", "Lin Reg", "Lin Reg (w/ confounders)", 
                   "Proximal (#NC=1)", "Proximal (#NC=3)", "Proximal (#NC=5)", "Proximal (#NC=10)", "Proximal (#NC=15)", "Proximal (#NC=20)"))

# effects$type = factor(effects$type,
#        levels = c('negative', 'positive'),
#        labels = c(    'Null', 'Alternative'))

dim(effects); head(effects)

```




# Compare Continuous Method Results



Histogram of estimates
```{r, fig.width=15, fig.height = 5}
ggplot(effects_continuous,
       aes(x = ATE, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)),  bins = 40) + # binwidth = .25) +
  geom_vline(aes(xintercept = 0), color = 'gray10', linewidth = .2) +
  scale_fill_manual(values = method_long_colors) +
  facet_grid(rows = vars(type), cols = vars(method, numNC), scales = 'free') + 
  labs(title = 'Histogram of Estimates',
       fill = 'Method')

ggsave(sprintf('%s/estimates_hist.pdf', plot_dir_continuous), height = 5, width= 15)
```


Histogram of p-values
```{r fig.width=15, fig.height = 5}
ggplot(effects_continuous,
       aes(x = pval, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)), binwidth = .02) +
  scale_x_continuous(limits = c(-.05, 1.05), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_fill_manual(values = method_long_colors) +
  facet_grid(rows = vars(type), cols = vars(method, numNC), scales = 'free') +
  labs(title = 'Histogram of p-values',
       x = 'ATE Estimate',
       fill = 'Method')

ggsave(sprintf('%s/pval_hist.pdf', plot_dir_continuous), height = 5, width= 15)
```

QQ-plot (basically)
```{r}
# config df for plotting
# the 'rejection_rate' column is also the 'theoretical' for the uniform (1/n, 2/n, ..., n/n)
plot_df = effects_continuous |> mutate(method_long = paste0(method, numNC)) |> group_by(type, method_long) |> reframe(pval=sort(pval), rejection_rate = (1:n())/n())
plot_df$method_long = factor(plot_df$method_long, 
       levels = c( "lmYANA",                 "lmYAUNA" ,       "2SLSpci2s1",       "2SLSpci2s3",       "2SLSpci2s5",       "2SLSpci2s10",       "2SLSpci2s15",       "2SLSpci2s20"),
       labels = c("Lin Reg", "Lin Reg (w/ confounders)", "Proximal (#NC=1)", "Proximal (#NC=3)", "Proximal (#NC=5)", "Proximal (#NC=10)", "Proximal (#NC=15)", "Proximal (#NC=20)"))

# plot_df$type = factor(plot_df$type,
#        levels = c('negative', 'positive'),
#        labels = c(    'Null', 'Alternative'))


#----- p-values: qqplot vs uniform = rejection rate by pval threshold ---------- 'pval_qqplot.pdf'
ggplot(plot_df,
       aes(x = pval, y = rejection_rate, color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  # geom_point() +
  geom_line(linewidth = 1, alpha = .9) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_color_manual(values = method_long_colors) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = 'Rejection Rate by P-value Threshold', 
       x = 'p-value threshold', y = 'rejection rate',
       color = 'Method') +
  facet_grid(rows = vars(type)) 
ggsave(sprintf('%s/pval_qqplot.pdf', plot_dir_continuous), height = 6, width= 6)


#----- p-values: log10 qqplot -------------------------------------------------- 'pval_qqplot_log.pdf'
p = ggplot(plot_df,
       aes(y = -log(pval, base = 10), x = -log(rejection_rate, base = 10), color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  # geom_line(linewidth = .3, alpha = .8) +
  geom_point(size = 1.5, alpha = .8) +
  # scale_x_continuous(limits = c(2, 3.5)) +
  # scale_y_continuous(limits = c(0, 200)) +
  scale_color_manual(values = method_long_colors) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = '-log(p-value) by -log(theoretical)', 
       x = latex2exp::TeX('-$log_{10}$(theoretical)'), y = latex2exp::TeX('-$log_{10}$(p-value)'),
       color = 'Method') +
  # facet_grid(rows = vars(type), scales = 'free') # facetted_pos_scales doesn't seem to work with facet_grid
  facet_wrap(vars(type), ncol=1, scales = 'free', strip.position = "right")
p

ggsave(sprintf('%s/pval_qqplot_log.pdf', plot_dir_continuous), height = 6, width= 6)


# use gg4x to set limits separately 
# https://stackoverflow.com/questions/72962172/custom-y-axis-breaks-of-facet-wrap/73006975#73006975
#----- p-values: log10 qqplot (Focus on same tail) ------------------------ 'pval_qqplot_log_tail1.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(.4, 2)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 2))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 40)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 40))  )
  )

ggsave(sprintf('%s/pval_qqplot_log_tail1.pdf', plot_dir_continuous), height = 6, width= 6)


#----- p-values: log10 qqplot (Focus on different tails) ---------------------------------- 'pval_qqplot_log_tail2.pdf'
p + ggh4x::facetted_pos_scales(x = list(
  type == 'Null'        ~ scale_x_continuous(limits = c(1, 3.25)),
  type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 2))
))
ggsave(sprintf('%s/pval_qqplot_log_tail2.pdf', plot_dir_continuous), height = 6, width= 6)

#----- p-values: log10 qqplot (Focus even more on different tails) ------------------------ 'pval_qqplot_log_tail3.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(1, 2)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 1.25))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 35)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 60))  )
  )

ggsave(sprintf('%s/pval_qqplot_log_tail3.pdf', plot_dir_continuous), height = 6, width= 6)
```








# Compare Count GLM Method Results










Histogram of estimates
```{r, fig.width=15, fig.height = 5}
ggplot(effects_count,
       aes(x = ATE, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)),  bins = 40) + # binwidth = .25) +
  geom_vline(aes(xintercept = 0), color = 'gray10', linewidth = .2) +
  scale_fill_manual(values = method_long_colors_count) +
  facet_grid(rows = vars(type), cols = vars(method_long), scales = 'free') + 
  labs(title = 'Histogram of Estimates',
       fill = 'Method')

ggsave(sprintf('%s/estimates_hist.pdf', plot_dir_count), height = 5, width= 15)
```


Histogram of p-values
```{r fig.width=15, fig.height = 5}
ggplot(effects_count,
       aes(x = pval, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)), binwidth = .02) +
  scale_x_continuous(limits = c(-.05, 1.05), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_fill_manual(values = method_long_colors_count) +
  facet_grid(rows = vars(type), cols = vars(method_long), scales = 'free') +
  labs(title = 'Histogram of p-values',
       x = 'ATE Estimate',
       fill = 'Method')

ggsave(sprintf('%s/pval_hist.pdf', plot_dir_count), height = 5, width= 15)
```

QQ-plot (basically)
```{r}
# config df for plotting
# the 'rejection_rate' column is also the 'theoretical' for the uniform (1/n, 2/n, ..., n/n)
plot_df = effects_count |> mutate(method_long = paste0(method, numNC)) |> group_by(type, method_long) |> reframe(pval=sort(pval), rejection_rate = (1:n())/n())
plot_df$method_long = factor(plot_df$method_long, 
       levels = c( "poisYANA",  "poisYAUNA", "nbYANA", "nbYAUNA"),
       labels = c("Poisson", "Poisson (w/ confounders)", "Negative Binomial", "Negative Binomial (w/ confounders)"))

# plot_df$type = factor(plot_df$type,
#        levels = c('negative', 'positive'),
#        labels = c(    'Null', 'Alternative'))


#----- p-values: qqplot vs uniform = rejection rate by pval threshold ---------- 'pval_qqplot.pdf'
ggplot(plot_df,
       aes(x = pval, y = rejection_rate, color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  # geom_point() +
  geom_line(linewidth = 1, alpha = .9) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_color_manual(values = method_long_colors_count) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = 'Rejection Rate by P-value Threshold', 
       x = 'p-value threshold', y = 'rejection rate',
       color = 'Method') +
  facet_grid(rows = vars(type)) 

ggsave(sprintf('%s/pval_qqplot.pdf', plot_dir_count), height = 6, width= 8)


#----- p-values: log10 qqplot -------------------------------------------------- 'pval_qqplot_log.pdf'
p = ggplot(plot_df,
       aes(y = -log(pval, base = 10), x = -log(rejection_rate, base = 10), color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  # geom_line(linewidth = .3, alpha = .8) +
  geom_point(size = 1.5, alpha = .8) +
  # scale_x_continuous(limits = c(2, 3.5)) +
  # scale_y_continuous(limits = c(0, 200)) +
  scale_color_manual(values = method_long_colors_count) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = '-log(p-value) by -log(theoretical)', 
       x = latex2exp::TeX('-$log_{10}$(theoretical)'), y = latex2exp::TeX('-$log_{10}$(p-value)'),
       color = 'Method') +
  # facet_grid(rows = vars(type), scales = 'free') # facetted_pos_scales doesn't seem to work with facet_grid
  facet_wrap(vars(type), ncol=1, scales = 'free', strip.position = "right")
p

ggsave(sprintf('%s/pval_qqplot_log.pdf', plot_dir_count), height = 6, width= 8)



# use gg4x to set limits separately 
# https://stackoverflow.com/questions/72962172/custom-y-axis-breaks-of-facet-wrap/73006975#73006975
#----- p-values: log10 qqplot (Focus on same tail) ------------------------ 'pval_qqplot_log_tail1.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(.4, 2.5)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 2.5))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 300)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 300))  )
  )

ggsave(sprintf('%s/pval_qqplot_log_tail1.pdf', plot_dir_count), height = 6, width= 8)


#----- p-values: log10 qqplot (Focus on different tails) ---------------------------------- 'pval_qqplot_log_tail2.pdf'
p + ggh4x::facetted_pos_scales(x = list(
  type == 'Null'        ~ scale_x_continuous(limits = c(1, 3.25)),
  type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 2))
))
ggsave(sprintf('%s/pval_qqplot_log_tail2.pdf', plot_dir_count), height = 6, width= 8)

#----- p-values: log10 qqplot (Focus even more on different tails) ------------------------ 'pval_qqplot_log_tail3.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(1, 2)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 1.25))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 35)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 60))  )
  )

ggsave(sprintf('%s/pval_qqplot_log_tail3.pdf', plot_dir_count), height = 6, width= 8)
```






# Compare continuous + count together (TODO: add sceptre)





Histogram of estimates
```{r, fig.width=20, fig.height = 5}
ggplot(effects,
       aes(x = ATE, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)),  bins = 40) + # binwidth = .25) +
  geom_vline(aes(xintercept = 0), color = 'gray10', linewidth = .2) +
  scale_fill_manual(values = method_long_colors_all) +
  facet_grid(rows = vars(type), cols = vars(method, numNC), scales = 'free') + 
  labs(title = 'Histogram of Estimates',
       fill = 'Method')

ggsave(sprintf('%s/estimates_hist.pdf', plot_dir_all), height = 5, width= 20)
```





Histogram of p-values
```{r fig.width=20, fig.height = 5}
ggplot(effects,
       aes(x = pval, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)), binwidth = .02) +
  scale_x_continuous(limits = c(-.05, 1.05), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_fill_manual(values = method_long_colors_all) +
  facet_grid(rows = vars(type), cols =  vars(method, numNC), scales = 'free') +
  labs(title = 'Histogram of p-values',
       x = 'ATE Estimate',
       fill = 'Method')

ggsave(sprintf('%s/pval_hist.pdf', plot_dir_all), height = 5, width= 20)
```






QQ-plot (basically)
```{r fig.height = 6, fig.width= 8}
# config df for plotting
# the 'rejection_rate' column is also the 'theoretical' for the uniform (1/n, 2/n, ..., n/n)
plot_df = effects |> mutate(method_long = paste0(method, numNC)) |> group_by(type, method_long) |> reframe(pval=sort(pval), rejection_rate = (1:n())/n())
plot_df$method_long = factor(plot_df$method_long, 
       levels = c("poisYANA",      "poisYAUNA", "nbYANA",           "nbYAUNA",                             "lmYANA",                            "lmYAUNA" ,       
                         "2SLSpci2s1",       "2SLSpci2s3",       "2SLSpci2s5",       "2SLSpci2s10",       "2SLSpci2s15",       "2SLSpci2s20"),
       labels = c( "Poisson", "Poisson (w/ confounders)", "Negative Binomial", "Negative Binomial (w/ confounders)", "Lin Reg", "Lin Reg (w/ confounders)", 
                   "Proximal (#NC=1)", "Proximal (#NC=3)", "Proximal (#NC=5)", "Proximal (#NC=10)", "Proximal (#NC=15)", "Proximal (#NC=20)"))

# plot_df$type = factor(plot_df$type,
#        levels = c('negative', 'positive'),
#        labels = c(    'Null', 'Alternative'))


#----- p-values: qqplot vs uniform = rejection rate by pval threshold ---------- 'pval_qqplot.pdf'
ggplot(plot_df,
       aes(x = pval, y = rejection_rate, color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  # geom_point() +
  geom_line(linewidth = 1, alpha = .8) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_color_manual(values = method_long_colors_all) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = 'Rejection Rate by P-value Threshold', 
       x = 'p-value threshold', y = 'rejection rate',
       color = 'Method') +
  facet_grid(rows = vars(type)) 

ggsave(sprintf('%s/pval_qqplot.pdf', plot_dir_all), height = 6, width= 8)


#----- p-values: log10 qqplot -------------------------------------------------- 'pval_qqplot_log.pdf'
p = ggplot(plot_df,
       aes(y = -log(pval, base = 10), x = -log(rejection_rate, base = 10), color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  # geom_line(linewidth = .3, alpha = .8) +
  geom_point(size = 1.5, alpha = .8) +
  # scale_x_continuous(limits = c(2, 3.5)) +
  # scale_y_continuous(limits = c(0, 200)) +
  scale_color_manual(values = method_long_colors_all) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = '-log(p-value) by -log(theoretical)', 
       x = latex2exp::TeX('-$log_{10}$(theoretical)'), y = latex2exp::TeX('-$log_{10}$(p-value)'),
       color = 'Method') +
  # facet_grid(rows = vars(type), scales = 'free') # facetted_pos_scales doesn't seem to work with facet_grid
  facet_wrap(vars(type), ncol=1, scales = 'free', strip.position = "right")
p

ggsave(sprintf('%s/pval_qqplot_log.pdf', plot_dir_all), height = 6, width= 8)




# use gg4x to set limits separately 
# https://stackoverflow.com/questions/72962172/custom-y-axis-breaks-of-facet-wrap/73006975#73006975
#----- p-values: log10 qqplot (Focus on same tail) ------------------------ 'pval_qqplot_log_tail1.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(.6, 2.5)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.6, 2.5))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 200)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 200))  )
  )

ggsave(sprintf('%s/pval_qqplot_log_tail1.pdf', plot_dir_all), height = 6, width= 8)


#----- p-values: log10 qqplot (Focus on different tails) ---------------------------------- 'pval_qqplot_log_tail2.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(1, 2.6)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.4, 1.5))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 300)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 100))   )  
  )
ggsave(sprintf('%s/pval_qqplot_log_tail2.pdf', plot_dir_all), height = 6, width= 8)

#----- p-values: log10 qqplot (Focus even more on different tails) ------------------------ 'pval_qqplot_log_tail3.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(1.25, 2)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(.7, 1.25))  ),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 60)),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 60))  )
  )

ggsave(sprintf('%s/pval_qqplot_log_tail3.pdf', plot_dir_all), height = 6, width= 8)
```











































# Extra Code


```{r echo=FALSE, include=FALSE, eval=FALSE}
test = MASS::glm.nb('Sepal.Width ~ Petal.Length + offset(Petal.Width)', iris)

summary(test)$coefficients



pois_YA = glm('Y ~ A + offset(log(n_umis))', test |> rename(n_umis = offset), family = 'poisson')


dim(test)
head(test)



```



