---
title: "3.X_jin_visualize"
format: 
  html:
    theme: flatly
    toc: true
    toc-depth: 4
    fig-format: svg 
    embed-resources: true
    self-contained-math: true
editor: source
execute: 
  echo: false
  warning: false
  error: false
---



Visualize quick jin-2020 results: linear reg, neg bin, prox with PCA



# Load


```{r output=FALSE}
# Libraries and Parameters
# ========================================================================================================================================================================
suppressPackageStartupMessages(library(assertthat)) # for some assert statements
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggh4x))


theme_set(theme_cowplot() +
            theme(plot.title = element_text(hjust = .5),
                  plot.subtitle = element_text(hjust = .5),
                  strip.background = element_rect(fill = "white", color = 'black'),
                  panel.grid.minor = element_blank(),
                  panel.grid.major = element_blank()))


# === === === === === === === === === === === === === === === === === === === === === === === === === 
# parameters
DEVICE                = 'macbook'
AYZW_setting_name     = 'exampledata'

source('../PATHS.R') # load in data_dir and save_dir and CODE_DIR, depending on DEVICE value

# --- Folder ---
plot_dir = sprintf('%s/AY/%s/plots/', save_dir, AYZW_setting_name)
dir.create(plot_dir, showWarnings = FALSE, recursive=TRUE)

# === === === === === === === === === === === === === === === === === === === === === === === === === 

# load chosen AYZW names
AY   = read.csv(sprintf('%s/AY/%s/AY.csv', save_dir, AYZW_setting_name))


effects = read.csv(sprintf('%s/AY/exampledata/effects.csv', save_dir))
effects[effects$method == '2SLSpci2s', 'method'] = 'proximal' # replace 2SLSpci2s with proximal



method_long_order = c('lmNANA', 'negbinNANA', paste0('proximal', 'PCA', c(1, 3, 5, 10, 15, 20)))
method_long_nicenames = c("Lin Reg", "Neg Bin", paste0('Proximal: PCA (#NC=', c(1, 3, 5, 10, 15, 20), ')'))
method_long_colors = c('red3', 'darkorchid', colorRampPalette(c('white', 'seagreen'))(8)[3:8])
names(method_long_colors) = method_long_nicenames


effects = effects |> 
             mutate(method_long_raw = paste0(method, NC_type, numNC),
                        method_long = factor(method_long_raw, levels = method_long_order, labels = method_long_nicenames))

effects$type = factor(effects$type,
       levels = c('discovery', 'positive'),
       labels = c('Discovery', 'Alternative'))
```





# Plots

## Histogram of estimates and p-values

Histogram of estimates
```{r, fig.width=10, fig.height = 10}

plot_df = effects

p = ggplot(plot_df,
       aes(x = ATE, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)), binwidth = .05) + # bins = 50) +
  geom_vline(aes(xintercept = 0), color = 'gray15', linewidth = .4) +
  coord_cartesian(xlim = c(-2, 1), ylim = c(0, 3)) +
  scale_y_continuous(breaks = 0:2, expand = expansion(mult = c(0, .05))) +
  # scale_fill_manual(guide = guide_legend(ncol = 1)) +
  facet_grid(cols = vars(type), 
             rows = vars(method, NC_type, numNC),  # vars(method_long), # vars(method, NC_type, numNC), 
             scales = 'free') + 
  labs(title = 'Histogram of Estimates',
       fill = 'Method') +
  theme(strip.text.y = element_text(size = 8), 
        axis.text.y = element_text(size = 8), 
        panel.spacing.x = unit(1, "lines"),
        panel.spacing.y = unit(0, "lines"))
p
ggsave(sprintf('%s/estimates_hist_tall.pdf', plot_dir), height = 10, width= 10)

```

```{r fig.width=12, fig.height = 5}
p + facet_grid(rows = vars(type), 
             cols = vars(method, NC_type, numNC), 
             scales = 'free')  +
  theme(strip.text.x = element_text(size = 8), 
        axis.text.x = element_text(size = 8), 
        panel.spacing.y = unit(1, "lines"),
        panel.spacing.x = unit(0, "lines"))
ggsave(sprintf('%s/estimates_hist_wide.pdf', plot_dir), height = 5, width= 12)
```


Histogram of p-values
```{r fig.width=10, fig.height = 10}

p = ggplot(plot_df,
       aes(x = pval, fill = method_long)) +
  geom_histogram(aes(y = after_stat(..density..)), binwidth = .020) + # bins = 50) +
  scale_x_continuous(limits = c(-.05, 1.05), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1'), 
                     expand = expansion(mult = c(.01, .01))) +
  # coord_cartesian(ylim = c(0, 3)) +
  scale_y_continuous( expand = expansion(mult = c(0, .05))) +
  scale_fill_manual(values = method_long_colors, guide = guide_legend(ncol = 1)) +
  facet_grid2(cols = vars(type), 
              rows = vars(method, NC_type, numNC), # vars(method_long), # vars(method, NC_type, numNC), 
             # labeller = labeller(method_raw=as_labeller(method_multiline_labeller)),
             axes = 'x', remove_labels = 'x', independent = 'y', shrink = TRUE,
             scales = 'free') + 
  labs(title = 'Histogram of p-values',
       x = 'p-value',
       fill = 'Method') +
  theme(strip.text.y = element_text(size = 8), 
        axis.text.y = element_text(size = 8), 
        panel.spacing.x = unit(1, "lines"),
        panel.spacing.y = unit(0, "lines"))
p

ggsave(sprintf('%s/pval_hist_tall.pdf', plot_dir), height = 10, width= 10)


# # # force same axes- does not look good, but gives perspective
# p + facet_grid2(cols = vars(type),
#              rows = vars(NC_type, numNC), # vars(method_long), # vars(method, NC_type, numNC),
#              axes = 'x', remove_labels = 'x', independent = 'y', shrink = TRUE,
#              scales = 'fixed')
```


```{r fig.width=13, fig.height = 4}
p + 
# facet_grid(rows = vars(type), 
#              cols = vars(method_raw),  # vars(method_long), # vars(method, NC_type, numNC), 
#              labeller = labeller(method_raw=as_labeller(method_multiline_labeller)),
#              scales = 'free')  +
    facet_grid2(rows = vars(type), 
                # cols = vars(method_raw), # vars(method_long), # vars(method, NC_type, numNC),
                cols = vars(method, NC_type, numNC),
             axes = 'x', remove_labels = 'x', independent = 'y', shrink = TRUE,
             scales = 'free') + 
  theme(strip.text.x = element_text(size = 8), 
        axis.text.x = element_text(size = 8), 
        panel.spacing.y = unit(1, "lines"),
        panel.spacing.x = unit(0, "lines"))
ggsave(sprintf('%s/pval_hist_wide.pdf', plot_dir), height = 4, width= 13)
```


```{r fig.width=13, fig.height=4}
# force same axes- does not look good, but gives perspective
p + 
  facet_grid(rows = vars(type),
             # cols = vars(method_raw),  # vars(method_long), # vars(method, NC_type, numNC),
             cols = vars(method, NC_type, numNC),
             # labeller = labeller(method_raw=as_labeller(method_multiline_labeller)),
             scales = 'free')  +
  theme(strip.text.x = element_text(size = 8), 
        axis.text.x = element_text(size = 8), 
        panel.spacing.y = unit(1, "lines"),
        panel.spacing.x = unit(0, "lines"))
ggsave(sprintf('%s/pval_hist_wide2.pdf', plot_dir), height = 4, width= 13)
```


## QQ-plots/Rejection Rates of p-values: Between Methods/Within Test Types


QQ-plot (basically)
```{r fig.height=3, fig.width=7}
# the 'rejection_rate' column is also the 'theoretical' for the uniform (1/n, 2/n, ..., n/n)
plot_df = effects |> 
          group_by(type, method_long) |> 
          reframe(pval=sort(pval), count=sum(!is.na(pval)), rejection_rate = (1:count)/count) 

#----- p-values: qqplot vs uniform = rejection rate by pval threshold (all numNC)  ---------- 'pval_qqplot.pdf'
ggplot(plot_df,
       aes(x = pval, y = rejection_rate, color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_line(linewidth = .4, alpha = .9, key_glyph = "rect") +
  geom_point(size=.2, alpha=.7, key_glyph = "rect") +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, .25, .5, .75, 1), labels = c('0', '.25', '.5', '.75', '1')) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_color_manual(values = method_long_colors, guide = guide_legend(ncol = 1)) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = 'Rejection Rate by P-value Threshold', 
       x = 'p-value threshold', y = 'rejection rate',
       color = 'Method') +
  facet_grid(cols = vars(type)) +
  theme(legend.text = element_text(size = 8), legend.key.size = unit(.4, units = 'cm'))
ggsave(sprintf('%s/pval_qqplot.pdf', plot_dir), height = 3, width= 7)




#----- p-values: log10 qqplot -------------------------------------------------- 'pval_qqplot_log.pdf'
p = ggplot(plot_df,
       aes(y = -log(pval+(1e-500), base = 10), x = -log(rejection_rate+(1e-500), base = 10), color = method_long)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_line(linewidth = .4, alpha = .8, key_glyph = 'rect') +
  geom_point(size = 1, alpha = .7, key_glyph = 'rect', stroke=NA) +
  # scale_x_continuous(limits = c(2, 3.5)) +
  # scale_y_continuous(limits = c(0, 200)) +
  scale_color_manual(values = method_long_colors, guide = guide_legend(ncol = 1)) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = '-log(p-value) by -log(Unif(0,1))', 
       x = latex2exp::TeX('theoretical -$log_{10}$(Unif(0,1))'), y = latex2exp::TeX('sample -$log_{10}$(p-value)'),
       color = 'Method') +
  facet_grid(cols = vars(type), scales = 'free') + # facetted_pos_scales doesn't seem to work with facet_grid
  # facet_wrap(vars(type), ncol=1, scales = 'free', strip.position = "right") +
  theme(legend.text = element_text(size = 8), legend.key.size = unit(.4, units = 'cm'))
p

ggsave(sprintf('%s/pval_qqplot_log.pdf', plot_dir), height = 3, width= 7)



# use gg4x to set limits separately 
# https://stackoverflow.com/questions/72962172/custom-y-axis-breaks-of-facet-wrap/73006975#73006975
#----- p-values: log10 qqplot (Focus on same tail) ------------------------ 'pval_qqplot_log_tail1.pdf'
p + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(0, 2)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(0, 2)),
    type == 'Discovery'   ~ scale_x_continuous(limits = c(0, 2))),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 7), oob=scales::squish),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 7), oob=scales::squish),
    type == 'Discovery'   ~ scale_y_continuous(limits = c(0, 7), oob=scales::squish))
  )

ggsave(sprintf('%s/pval_qqplot_log_tail1.pdf', plot_dir), height = 3, width= 7)


#----- p-values: log10 qqplot (Focus on different tails) ---------------------------------- 'pval_qqplot_log_tail2.pdf'
p + geom_line() + ggh4x::facetted_pos_scales(
  x = list(
    type == 'Null'        ~ scale_x_continuous(limits = c(0, 1)),
    type == 'Alternative' ~ scale_x_continuous(limits = c(0, 1)),
    type == 'Discovery'   ~ scale_x_continuous(limits = c(0, 1))),
  y = list(
    type == 'Null'        ~ scale_y_continuous(limits = c(0, 3), oob=scales::squish),
    type == 'Alternative' ~ scale_y_continuous(limits = c(0, 3), oob=scales::squish),
    type == 'Discovery'   ~ scale_y_continuous(limits = c(0, 3), oob=scales::squish))
  )

ggsave(sprintf('%s/pval_qqplot_log_tail2.pdf', plot_dir), height = 3, width= 7)

#----- p-values: log10 qqplot (Focus even more on different tails) ------------------------ 'pval_qqplot_log_tail3.pdf'


# ggsave(sprintf('%s/pval_qqplot_log_tail3.pdf', plot_dir), height = 3, width= 9)
```


## QQ-plots/Rejection Rates of p-values: Between Test Types/Within Methods

```{r fig.height=5, fig.width=10}
# the 'rejection_rate' column is also the 'theoretical' for the uniform (1/n, 2/n, ..., n/n)
plot_df = effects |> 
          filter(is.na(numNC) | numNC %in% c(1, 5, 10, 20)) |> 
          group_by(type, method_long) |> 
          reframe(pval=sort(pval), count=sum(!is.na(pval)), rejection_rate = (1:count)/count) 


#----- p-values: log10 qqplot -------------------------------------------------- 'pval_qqplot_log.pdf'
ggplot(plot_df, 
       aes(y = -log(pval+(1e-500), base = 10), x = -log(rejection_rate+(1e-500), base = 10), 
           color = method_long, linetype = type)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_line(            linewidth = .7, alpha = 1) +
  geom_point(size = 1, alpha = .7, key_glyph = 'rect', stroke=NA) +
  coord_cartesian(xlim=c(0, 1), ylim=c(0, 3)) +
  scale_color_manual(values = method_long_colors, guide = guide_legend(ncol = 1)) + #, labels = lapply(levels(plot_df$method_long), latex2exp::TeX)) +
  labs(title = '-log(p-value) by -log(Unif(0,1))', 
       x = latex2exp::TeX('theoretical -$log_{10}$(Unif(0,1))'), y = latex2exp::TeX('sample -$log_{10}$(p-value)'),
       color = 'Method', linetype = 'Test Type') +
  facet_wrap(facets = vars(method_long), scales = 'free') + # facetted_pos_scales doesn't seem to work with facet_grid
  theme(legend.text = element_text(size = 8), legend.key.size = unit(.4, units = 'cm'))

ggsave(sprintf('%s/pval_disc_vs_alt_qqplot_log_tail1.pdf', plot_dir), height = 5, width= 10)

```



## Focus on Positive/Alternative Tests
```{r fig.height = 5, fig.width = 8}


plot_df = effects |> filter(type == 'Alternative') |> mutate(AY_test = paste0(grna,'-', gene))

# set colors according to original lin reg pval
AY_idx_order = plot_df |> filter(method == 'negbin') |> arrange(pval) |> pull(AY_test)
AY_idx_colors = colorRampPalette(c('blue4', 'white'))(length(AY_idx_order) + 3)[4:(length(AY_idx_order)+3)]
names(AY_idx_colors) = AY_idx_order


plot_df = plot_df |> mutate(AY_test = factor(AY_test, levels = AY_idx_order))

p = ggplot(plot_df, 
       aes(x = method_long, y = pval, group = AY_test, color = AY_test)) + 
  geom_point() + 
  geom_line() +
  scale_color_manual(values = AY_idx_colors) +
  labs(title = 'p-value across methods', x = 'method', y = 'p-value', color = 'grna-gene test') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 8), legend.key.size = unit(.4, units = 'cm'))
p
ggsave(sprintf('%s/alttests_pval_by_method.pdf', plot_dir), height = 5, width= 8)



# --------- log scale  -----------


p + scale_y_log10()
ggsave(sprintf('%s/alttests_pval_by_method_log10.pdf', plot_dir), height = 5, width= 8)



```















